### ISSUE TITLE
질문입니다. (상태 전달)

### ISSUE THREAD

**Issue by sjndowair** [sjndowair/movvy#8]
모달의 상태를 부모 컴포넌트에서 관리하고 자식에게 props를 전달해주는 과정에서 체크박스의 상태를 전달해주기위해 타입을 
interface IModalProps{
setIsCheckedNotToday: (pre: boolean) => void
}
로 작성 시 
pre의 값은 any라는 현상이 지속적으로 발생하는데 찾아보니
setIsCheckedNotToday: React.Dispatch<React.SetStateAction<boolean>>;
의 값은 정상적으로 동작하는걸 확인 했는데 
(pre: boolean) 을 직접적으로 정의 할 시 왜 boolean값으로 지정이 되지 않는걸까요?
<img width="753" alt="image" src="https://github.com/user-attachments/assets/ba4390ab-2f02-4ed5-b90d-25eca6c9ad8f">

**Comment by songforthemute** [comment]
1. 프롭은 만능 열쇠가 아니다. 결국 프롭이라는 상속받아야하는 상태가 생겼고, 여기에 컴포넌트가 의존하게 된다는 것.

2. 커스텀 훅에 대해서 알아보기.

3. 매개변수 타입이 다르다.
